export const env = {
  AWS_REGION: process.env.AWS_REGION!,
  AWS_ENDPOINT: process.env.AWS_ENDPOINT,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID!,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY!,
  AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME!,
  NEXT_PUBLIC_AWS_BUCKET_NAME: process.env.NEXT_PUBLIC_AWS_BUCKET_NAME!,
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID!,
  NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY!,
  NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST!,
  NEXT_PUBLIC_BREVO_CLIENT_KEY: process.env.NEXT_PUBLIC_BREVO_CLIENT_KEY!,
  NEXT_PUBLIC_BREVO_ENABLED: process.env.NEXT_PUBLIC_BREVO_ENABLED!,
  BREVO_API_KEY: process.env.BREVO_API_KEY!,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!,
} as const;
